In [2]:
import torch

c:\Users\euna\miniconda3\envs\vig_project\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [6]:
out_features

1

In [ ]:
 self.k = 9 # neighbor num (default:9)
            self.conv = 'mr' # graph conv layer {edge, mr}
            self.act = 'gelu' # activation layer {relu, prelu, leakyrelu, gelu, hswish}
            self.norm = 'batch' # batch or instance normalization {batch, instance}
            self.bias = True # bias of conv layer True or False
            self.dropout = 0.0 # dropout rate
            self.use_dilation = True # use dilated knn or not
            self.epsilon = 0.2 # stochastic epsilon for gcn
            self.use_stochastic = False # stochastic for gcn, True or False
            self.drop_path = drop_path_rate
            self.blocks = [2,2,6,2] # number of basic blocks in the backbone
            self.channels = [48, 96, 240, 384] # number of channels of deep features
            self.n_classes = num_classes # Dimension of out_channels
            self.emb_dims = 1024 # Dimension of embeddings


In [ ]:
num_features = [int(embed_dim * 2 ** i) for i in range(self.num_layers)]

In [1]:
2**3

8

In [3]:
import torch
a = torch.Tensor([1,2,3,4,5])
b = a[:10]
print(b)

tensor([1., 2., 3., 4., 5.])


In [1]:
1333//4


333

In [2]:
4 * (1333//4)

1332

In [3]:
1332//4

333

In [4]:
sum([2,2,6,2])

12

In [6]:
print(False is None)

False


In [7]:
print(None is None)

True


In [10]:
import torch

c:\Users\euna\miniconda3\envs\vig_project\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [12]:
a = torch.Tensor([[[0, 1, 0],
                    [0,2,0],
                    [0,3,0]],
                    [[0,4,0],
                    [0,5,0],
                    [0,6,0]]])
print(a.shape)

torch.Size([2, 3, 3])


In [18]:
x_inner = -2*torch.matmul(a, a.transpose(2, 1))
x_square = torch.sum(torch.mul(a, a), dim=-1, keepdim=True)

print(x_inner)
print(x_inner.shape)

tensor([[[ -2.,  -4.,  -6.],
         [ -4.,  -8., -12.],
         [ -6., -12., -18.]],

        [[-32., -40., -48.],
         [-40., -50., -60.],
         [-48., -60., -72.]]])
torch.Size([2, 3, 3])


In [17]:
print(x_square)
print(x_square.shape)

tensor([[[ 1.],
         [ 4.],
         [ 9.]],

        [[16.],
         [25.],
         [36.]]])
torch.Size([2, 3, 1])


In [24]:
dist = x_square + x_inner + x_square.transpose(2, 1)
print(dist)

tensor([[[0., 1., 4.],
         [1., 0., 1.],
         [4., 1., 0.]],

        [[0., 1., 4.],
         [1., 0., 1.],
         [4., 1., 0.]]])


In [22]:
nn_val, nn_idx = torch.topk(-dist, k=2)

In [23]:
nn_val

tensor([[[-0., -1.],
         [-0., -1.],
         [-0., -1.]],

        [[-0., -1.],
         [-0., -1.],
         [-0., -1.]]])

In [25]:
nn_idx

tensor([[[0, 1],
         [1, 0],
         [2, 1]],

        [[0, 1],
         [1, 0],
         [2, 1]]])

In [28]:
b = torch.Tensor([[[[1, 2, 3]],
              [[4, 5, 6]],
              [[7, 8, 9]]]])
print(b.shape)
b = b[:,:,:,::1]
print(b.shape)
print(b)

torch.Size([1, 3, 1, 3])
torch.Size([1, 3, 1, 3])
tensor([[[[1., 2., 3.]],

         [[4., 5., 6.]],

         [[7., 8., 9.]]]])


In [30]:
idx = torch.arange(0, 3).repeat(2,2,1)
print(idx.shape)

torch.Size([2, 2, 3])


In [38]:
import torch.nn as nn
in_dim = 3
out_dim = 768

m = nn.Sequential(
            nn.Conv2d(in_dim, out_dim//2, 3, stride=2, padding=1),
            

            nn.Conv2d(out_dim//2, out_dim, 3, stride=2, padding=1),
            nn.Conv2d(out_dim, out_dim, 3, stride=1, padding=1),
        )
input = torch.randn(2, 3, 1333, 800)
output1 = m[0](input)
output2 = m[1](output1)
output3 = m[2](output2)

In [39]:
print(output1.shape)
print(output2.shape)
print(output3.shape)

torch.Size([2, 384, 667, 400])
torch.Size([2, 768, 334, 200])
torch.Size([2, 768, 334, 200])


In [41]:
nn.Parameter(torch.zeros(1, 80, 1333//4, 800//4)).shape



torch.Size([1, 80, 333, 200])

In [6]:
a = torch.arange(0,2).repeat(1, 2, 1)
print(a)
print(a.shape)

tensor([[[0, 1],
         [0, 1]]])
torch.Size([1, 2, 2])


In [20]:
a = torch.randn((2,2))
b = torch.randn((2,2))

x1, _= torch.max(a-b,0)
x2, _ = torch.max(a-b,-1)

x3, _= torch.max(a-b,0, keepdim=True)
x4, _ = torch.max(a-b,-1, keepdim=True)

In [21]:
a-b

tensor([[ 0.0522, -1.3117],
        [-1.2525, -1.0966]])

In [22]:
print(x1)
print(x2)
print(x3)
print(x4)

tensor([ 0.0522, -1.0966])
tensor([ 0.0522, -1.0966])
tensor([[ 0.0522, -1.0966]])
tensor([[ 0.0522],
        [-1.0966]])


In [24]:
a = torch.randn((2,1,3136,9))
print(a[0].shape)

torch.Size([1, 3136, 9])


In [26]:
torch.tensor([1,1,1]) - torch.tensor([1, 0, 1])

tensor([0, 1, 0])